---
title: "Introduction to geneXplainR"
subtitle: "An R client for the geneXplain platform"
author: "Philip Stegmaier"
date: "`r Sys.Date()`"
show_toc: true
output:
  rmarkdown::html_vignette:
    toc: yes
vignette: >
  %\VignetteIndexEntry{geneXplainR package}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

The geneXplainR package provides an R client for the 
[geneXplain platform](http://genexplain.com/genexplain-platform/) [1]. 
The geneXplain platform is an online toolbox and workflow management 
system for a broad range of bioinformatic and systems biology applications.
The platform is well-known for its upstream analysis [2], that has been
developed to identify causal signalling molecules on the basis of experimental data
like expression measurements.

geneXplainR is based on and extends the [rbiouml](https://cran.r-project.org/web/packages/rbiouml/index.html) package.
A goal of this project is to add functionality that helps to make building R pipelines that use the geneXplain platform easier.

# Basic usage

A typical session with the geneXplain platform consists of signing into a valid user account
and following by performing computational analyses in the user workspace.

## Login

It is necessary to create a user account to obtain login credentials. A user account can be created for free
[here](http://genexplain.com/genexplain-platform-registration/). Through the web interface one can also access
the platform as *demo* user. The platform login is reachable through [this web page](http://genexplain.com/log-in/).

Having a user account, a session with the geneXplainR client commences with loading the library and
submitting login credentials to the server of choice using the *gx.login* function.

```{r eval=FALSE}
library(geneXplainR)
# Note that words within placeholders (<...>) need to be replaced.
gx.login("<server>","<user>","<password>")
```


