#
# Copyright (c) 2018 geneXplain GmbH, Wolfenbuettel, Germany
# Author: Philip Stegmaier, philip.stegmaier@genexplain.com
#
# Fetches a table generated by functional classification analysis and
# extracts gene sets
#
# Input table with parameters should consist of two tab-separated 
# key (left) and value (right) columns and no header with the following elements:
#
# +------------------+-------------------------------------------------------------------------+
# | user             | login user (default: empty)                                             |
# | password         | login password (default: empty)                                         |
# | server           | https://platform.genexplain.com                                         |
# | funClassTable    | platform path of functional classification table, required, no default  |
# | geneSetPath      | platform path of folder for output gene sets, required, no default      |
# | geneSetFolder    | name of folder for output gene sets, (default: fun_class_gene_sets)     |
# | species          | species to specify for import (default: Human (Homo sapiens)            |
# | localTableFile   | local export path for classification table, table will be exported here |
# |                  | (default: temp_fc_table.txt)                                            |
# | minGroupSize     | minimal size of groups to consider (default: 1)                         |
# | maxGroupSize     | maximal size groups to consider (default: 1e10)                         |
# | minHits          | min. number of hits to consider (default: 1)                            |
# | maxHits          | max. number of hits to consider (default: 1e10)                         |
# | maxAdjustedPval  | cutoff for adjusted P-value (default: 1)                                |
# +------------------+-------------------------------------------------------------------------+
#
library(geneXplainR)
args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 1) {
    stop("Please provide a file with configuration parameter table")
}
params <- read.table(args[1], header=F, sep="\t", row.names=1)
getParameter <- function(value, defaultVal) {
    V <- value
    if (is.na(value)) {
        V <- defaultVal
    }
    V
}
funClassTable <- as.character(params['funClassTable',1])
gx.login(as.character(params['server',1]),
         as.character(params['user',1]),
         as.character(params['password',1]))
localTable  <- getParameter(as.character(params['localTableFile',1]), "temp_fc_table.txt")
geneSetPath <- getParameter(as.character(params['geneSetPath',1]), "")
if (geneSetPath == "") {
    stop("Missing parameter geneSetPath")
}
geneSetFolder <- getParameter(as.character(params['geneSetFolder',1]), "fun_class_gene_sets")
species       <- getParameter(as.character(params['species',1]), "Human (Homo sapiens)")
gx.export(funClassTable, 
          "Tab-separated text (*.txt)",
          list(columns = c("ID", "Title", "Number of hits", "Group size", "Expected hits", "P-value", "Adjusted P-value", "Hits")),
          localTable)
fctable <- read.table(localTable, header=T, sep="\t", quote="")
minGroupSize <- getParameter(as.numeric(as.character(params['minGroupSize',1])), 1)
maxGroupSize <- getParameter(as.numeric(as.character(params['maxGroupSize',1])), 1e10)
minHits      <- getParameter(as.numeric(as.character(params['minHits',1])), 1)
maxHits      <- getParameter(as.numeric(as.character(params['maxHits',1])), 1e10)
maxAdjPval   <- getParameter(as.numeric(as.character(params['maxAdjustedPval',1])), 1.0)
fctable <- subset(fctable, Number.of.hits >= minHits & 
                  Number.of.hits <= maxHits & 
                  Group.size >= minGroupSize & 
                  Group.size <= maxGroupSize & 
                  Adjusted.P.value <= maxAdjPval)
gx.createFolder(geneSetPath, geneSetFolder)
for (r in 1:nrow(fctable)) {
    genes  <- gsub("]","",gsub("[","",strsplit(as.character(fctable$Hits[r]), ",", fixed=T)[[1]], fixed=T),fixed=T)
    gsName <- paste0(as.character(fctable$ID[r]),"_",as.character(fctable$Title[r]))
    name   <- gsub("\\W+","_",substring(gsName, 1, min(nchar(gsName),80)))
    print(name)
    write.table(data.frame(Gene=gsub("\"","",genes,fixed=T)), file=paste0(name,"_gene_set.txt"), quote=F, row.names=F, sep="\t")
    gx.import(paste0(name,"_gene_set.txt"),
              paste0(geneSetPath,"/",geneSetFolder),
              "Tabular (*.txt, *.xls, *.tab, etc.)",
              list(delimiterType="\t",headerRow=1,dataRow=2,
                   tableType="Genes: Ensembl", columnForID="Gene",species=species)
              )
}
